parameters:
    # Listeners
    cpasimusante.simupoll.simupoll_listener.class: CPASimUSante\SimupollBundle\Listener\SimupollResourceListener

    # Controllers
    cpasimusante.simupoll.simupoll_controller.class: CPASimUSante\SimupollBundle\Controller\SimupollController

    # Form types
    cpasimusantesimupoll.simupoll_form.class: CPASimUSante\SimupollBundle\Form\SimupollType

    # Services types
    cpasimusante.simupoll.simupoll_services.class: CPASimUSante\SimupollBundle\Services\SimupollServices
