# services:
#     # Simupoll controller
#     cpasimusante.simupoll.simupoll_controller:
#         class: %cpasimusante.simupoll.simupoll_controller.class%
#         calls:
#             - [ setContainer, [ @service_container ]]
#         arguments:
#             simupollManager: @cpasimusante.simupoll.simupoll_manager
