services:
    # Simupoll type
    cpasimusantesimupoll.simupoll_form:
        class:  %cpasimusantesimupoll.simupoll_form.class%
        tags:
          - { name: form.type, alias: cpasimusante_simupoll }
