# services:
#     # Simupoll type
#     cpasimusante.simupoll.simupoll_manager:
#         class:  %cpasimusante.simupoll.simupoll_manager.class%
#         arguments:
#             objectManager:   @claroline.persistence.object_manager
