services:
    # Simupoll services
    cpasimusante.simupoll.simupoll_services:
        class: %cpasimusante.simupoll.simupoll_services.class%
        arguments:
            objectManager:   @doctrine.orm.entity_manager
            securityAuth:    @security.authorization_checker
#            securityToken:   @security.token_storage
#            resourceManager: @claroline.manager.resource_manager
#            utils:           @claroline.security.utilities
