<?php

namespace CPASimUSante\SimupollBundle\Repository;

/**
 * ResponseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnswerRepository extends \Doctrine\ORM\EntityRepository
{
    public function getSimupollAllResponsesForAllUsersQuery($simupollId, $order)
    {
        return $this->getQuerySimupollAllResponsesForAllUsers($simupollId, $order)->getResult();
    }
    /**
     *
     * @return array
     */
    public function getQuerySimupollAllResponsesForAllUsers($simupollId, $order)
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('a')
            ->from('CPASimUSante\\SimupollBundle\\Entity\\Answer', 'a')
            ->join('a.paper', 'p')
            ->join('p.simupoll', 's')
            ->where('s.id = :sid')
//            ->orderBy($order, 'ASC')
            ->setParameters(array('sid' => $simupollId));
        return $qb->getQuery();
    }
}
