<?php

namespace CPASimUSante\SimupollBundle\Repository;

/**
 * StatcategorygroupRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatcategorygroupRepository extends \Doctrine\ORM\EntityRepository
{
}
